openapi: 3.0.1
info:
  title: ê·¸ë¦°ë£¸ API DOCUMENT
  description: ê·¸ë¦°ë£¸ api ëª…ì„¸ì„œì…ë‹ˆë‹¤.
  version: 0.1.0
servers:
- url: http://localhost:8080
- url: https://greenroom-server:8080
- url: http://greenroom-server:8080
tags: []
paths:
  /api/auth/login:
    post:
      tags:
      - ğŸ˜ AUTH-ì¸ì¦/ì¸ê°€
      summary: ë¡œê·¸ì¸ ìš”ì²­ api
      description: email&password ê¸°ë°˜ ì¼ë°˜ ë¡œê·¸ì¸ api
      operationId: ë¡œê·¸ì¸
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/api-auth-login486549215"
            examples:
              ë¡œê·¸ì¸-ì„±ê³µ:
                value: "{\"email\":\"testEmail@gmail.com\",\"password\":\"!123456\"\
                  }"
              ë¡œê·¸ì¸_FAIL_PASSWORD_NOT_MATCHED:
                value: "{\"email\":\"testEmail@gmail.com\",\"password\":\"!1234567890\"\
                  }"
              ë¡œê·¸ì¸_FAIL_USER_NOT_FOUND:
                value: "{\"email\":\"testEmail@gmail.com\",\"password\":\"!123456\"\
                  }"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-997914088"
              examples:
                ë¡œê·¸ì¸-ì„±ê³µ:
                  value: "{\"status\":\"OK\",\"code\":\"A001\",\"data\":{\"email\"\
                    :\"testEmail@gmail.com\",\"accessToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6IkdVRVNULEdFTkVSQUwiLCJleHAiOjE3MzYyMzc4OTd9.EoynTLzMrc0ZUvyiSeN9AdLl5zrSgBKd2gsiFOVrWOjAYevYMSugh4j_Jg4vHea1fTTHIlRJ5mIaWB-enfqn6w\"\
                    ,\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiZXhwIjoxNzM3NDQzODk3fQ.V0Wocm2mhmQlukRrvMcztBwhp1uSF8eMEDEt58Xnzd0eKO_hwrfTXsFBre20yXf8TjJaZ1O3AFZIHkm2rzP7jA\"\
                    }}"
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-2094128924"
              examples:
                ë¡œê·¸ì¸_FAIL_PASSWORD_NOT_MATCHED:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C017\",\"data\":null}"
        "404":
          description: "404"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-2094128924"
              examples:
                ë¡œê·¸ì¸_FAIL_USER_NOT_FOUND:
                  value: "{\"status\":\"NOT_FOUND\",\"code\":\"C001\",\"data\":null}"
  /api/auth/signup:
    post:
      tags:
      - ğŸ˜ AUTH-ì¸ì¦/ì¸ê°€
      summary: íšŒì›ê°€ì… ìš”ì²­ api
      description: emailê³¼ passwordë¡œ íšŒì›ê°€ì…ì„ ìš”ì²­í•©ë‹ˆë‹¤. ì¸ì¦ëœ emailë§Œ íšŒì›ê°€ì…ì´ ê°€ëŠ¥í•©ë‹ˆë‹¤.
      operationId: íšŒì›ê°€ì…
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/api-auth-login486549215"
            examples:
              íšŒì›ê°€ì…-ì„±ê³µ:
                value: "{\"email\":\"testEmail@gmail.com\",\"password\":\"!123456\"\
                  }"
              íšŒì›ê°€ì…_FAIL_EMAIL_NOT_VERIFIED:
                value: "{\"email\":\"emailnotvierified@gmail.com\",\"password\":\"\
                  !123456\"}"
              íšŒì›ê°€ì…_FAIL_USER_ALREAD_EXISTS:
                value: "{\"email\":\"testEmail@gmail.com\",\"password\":\"!123456\"\
                  }"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-2094128924"
              examples:
                íšŒì›ê°€ì…-ì„±ê³µ:
                  value: "{\"status\":\"CREATED\",\"code\":\"A001\",\"data\":null}"
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-2094128924"
              examples:
                íšŒì›ê°€ì…_FAIL_EMAIL_NOT_VERIFIED:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C023\",\"data\":null}"
                íšŒì›ê°€ì…_FAIL_USER_ALREAD_EXISTS:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C002\",\"data\":null}"
  /api/auth/tokens:
    put:
      tags:
      - ğŸ˜ AUTH-ì¸ì¦/ì¸ê°€
      summary: jwt í† í° ê°±ì‹  ìš”ì²­ api
      description: refresh tokenì„ í†µí•´ access token & refresh token ëª¨ë‘ ê°±ì‹ 
      operationId: jwtToken_ì¬ë°œê¸‰_
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/api-auth-login486549215"
            examples:
              jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_EXPIRED:
                value: "{\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6W3siYXV0aG9yaXR5IjoiZ3Vlc3QifSx7ImF1dGhvcml0eSI6ImdlbmVyYWwifV0sImV4cCI6MTczNjIzNDI5Nn0.xjO5LW2vbAMRvaI9KyxAQs0_Gngt14Kre3Gb5cc8JTMavqg7mhB_2fTFz7tJdVJ_sL_C-ZH7i2bgdTAe_MUM-A\"\
                  }"
              jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_INVALID:
                value: "{\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6W3siYXV0aG9yaXR5IjoiZ3Vlc3QifSx7ImF1dGhvcml0eSI6ImdlbmVyYWwifV0sImV4cCI6MTczNjIzNDI5Nn0.rUz1ZroQ5ygDqiZnZwXl9fl722tOpUBcE4yujEHrESJsbNbNO4yxsOHLaUt_xz1UFqqEn_Ja-4hUYDRDepRLgA\"\
                  }"
              jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_NOT_EXISTS:
                value: "{\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6W3siYXV0aG9yaXR5IjoiZ3Vlc3QifSx7ImF1dGhvcml0eSI6ImdlbmVyYWwifV0sImV4cCI6MTczNjIzNDI5OH0.kp1GWKy-PGOrDJNxqX7pz_cIPSFwnckqC2OshXyaD697ew_DKA11FwctYW9Zye-kxjSOF30lTouA3ZuqFEzqQw\"\
                  }"
              jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_NOT_MATCHED:
                value: "{\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6W3siYXV0aG9yaXR5IjoiZ3Vlc3QifSx7ImF1dGhvcml0eSI6ImdlbmVyYWwifV0sImV4cCI6MTczNjIzNDI5OH0.kp1GWKy-PGOrDJNxqX7pz_cIPSFwnckqC2OshXyaD697ew_DKA11FwctYW9Zye-kxjSOF30lTouA3ZuqFEzqQw\"\
                  }"
              jwtToken_ì¬ë°œê¸‰_FAIL_USER_NOT_FOUND:
                value: "{\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6W3siYXV0aG9yaXR5IjoiZ3Vlc3QifSx7ImF1dGhvcml0eSI6ImdlbmVyYWwifV0sImV4cCI6MTczNjIzNDI5OH0.kp1GWKy-PGOrDJNxqX7pz_cIPSFwnckqC2OshXyaD697ew_DKA11FwctYW9Zye-kxjSOF30lTouA3ZuqFEzqQw\"\
                  }"
              jwtToken_ì¬ë°œê¸‰_SUCCESS:
                value: "{\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiZXhwIjoxNzM3NDQzODkwfQ.ogPi0B6oWtixBdBZ6UPohG9Apx-LI8LEQoP_IhbYJXN71G7OaEOU9P9hXUieeIu5iD0GNXoGlUbIj1F6cfyggg\"\
                  }"
      responses:
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-2094128924"
              examples:
                jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_EXPIRED:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C005\",\"data\":null}"
                jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_INVALID:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C009\",\"data\":null}"
                jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_NOT_MATCHED:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C007\",\"data\":null}"
        "404":
          description: "404"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-2094128924"
              examples:
                jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_NOT_EXISTS:
                  value: "{\"status\":\"NOT_FOUND\",\"code\":\"C026\",\"data\":null}"
                jwtToken_ì¬ë°œê¸‰_FAIL_USER_NOT_FOUND:
                  value: "{\"status\":\"NOT_FOUND\",\"code\":\"C001\",\"data\":null}"
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-997914088"
              examples:
                jwtToken_ì¬ë°œê¸‰_SUCCESS:
                  value: "{\"status\":\"OK\",\"code\":\"A001\",\"data\":{\"email\"\
                    :\"testEmail@gmail.com\",\"accessToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6IkdVRVNULEdFTkVSQUwiLCJleHAiOjE3MzYyMzc4OTB9.kAAYpAGA8lR3M2AEyO7RP6kpvHG7k8xHmjjq7Kh1dKmLYPlTbZ15-oUYaviVpzPfCNlB7sWj02OgehryoPA2oQ\"\
                    ,\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiZXhwIjoxNzM3NDQzODkwfQ.ogPi0B6oWtixBdBZ6UPohG9Apx-LI8LEQoP_IhbYJXN71G7OaEOU9P9hXUieeIu5iD0GNXoGlUbIj1F6cfyggg\"\
                    }}"
  /api/auth/email/authentication:
    put:
      tags:
      - ğŸ˜ AUTH-ì¸ì¦/ì¸ê°€
      summary: ì´ë©”ì¼ ì¸ì¦ ìš”ì²­ api
      description: ì´ë©”ì¼ ì¸ì¦ìš© ë”¥ë§í¬ ë©”ì¼ ì „ì†¡ & ì¸ì¦ ì½”ë“œ ìƒì„± api
      operationId: ì´ë©”ì¼ì¸ì¦_
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/api-auth-login486549215"
            examples:
              ì´ë©”ì¼ì¸ì¦_FAIL_ALREADY_VERIFIED_EMAIL:
                value: "{\"redirectUrl\":\"http://localhost:8080\",\"email\":\"emailTest@gmail.com\"\
                  }"
              ì´ë©”ì¼ì¸ì¦_FAIL_EXCEED_NUMBER_OF_TRIAL_VERIFICATION:
                value: "{\"redirectUrl\":\"http://localhost:8080\",\"email\":\"emailTest@gmail.com\"\
                  }"
              ì´ë©”ì¼ì¸ì¦_FAIL_FAIL_TO_SEND_EMAIL:
                value: "{\"redirectUrl\":\"http://localhost:8080\",\"email\":\"mygongjoo@naver.com\"\
                  }"
              ì´ë©”ì¼ì¸ì¦_FAIL_INVALID_EMAIL_CONTENT:
                value: "{\"redirectUrl\":\"http://localhost:8080\",\"email\":\"myr@@@@naver.com\"\
                  }"
              ì´ë©”ì¼ì¸ì¦_FAIL_VERIFIED_USER_ALREADY_EXISTS:
                value: "{\"redirectUrl\":\"http://localhost:8080\",\"email\":\"emailTest@gmail.com\"\
                  }"
              ì´ë©”ì¼ì¸ì¦_SUCCESS:
                value: "{\"redirectUrl\":\"http://localhost:8080\",\"email\":\"emailTest@gmail.com\"\
                  }"
      responses:
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-2094128924"
              examples:
                ì´ë©”ì¼ì¸ì¦_FAIL_ALREADY_VERIFIED_EMAIL:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C025\",\"data\":null}"
                ì´ë©”ì¼ì¸ì¦_FAIL_EXCEED_NUMBER_OF_TRIAL_VERIFICATION:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C019\",\"data\":null}"
                ì´ë©”ì¼ì¸ì¦_FAIL_INVALID_EMAIL_CONTENT:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C024\",\"data\":null}"
                ì´ë©”ì¼ì¸ì¦_FAIL_VERIFIED_USER_ALREADY_EXISTS:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C018\",\"data\":null}"
        "500":
          description: "500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-2094128924"
              examples:
                ì´ë©”ì¼ì¸ì¦_FAIL_FAIL_TO_SEND_EMAIL:
                  value: "{\"status\":\"INTERNAL_SERVER_ERROR\",\"code\":\"D002\"\
                    ,\"data\":null}"
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-2094128924"
              examples:
                ì´ë©”ì¼ì¸ì¦_SUCCESS:
                  value: "{\"status\":\"OK\",\"code\":\"A001\",\"data\":null}"
  /api/auth/email/token/authentication:
    put:
      tags:
      - ğŸ˜ AUTH-ì¸ì¦/ì¸ê°€
      summary: ì´ë©”ì¼ í† í° ê²€ì¦ ìš”ì²­ api
      description: ì´ë©”ì¼ ë§í¬ë¥¼ í†µí•´ ì œê³µë°›ì€ í† í°ì„ ê²€ì¦í•˜ëŠ” api
      operationId: ì´ë©”ì¼í† í°ê²€ì¦_
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/api-auth-login486549215"
            examples:
              ì´ë©”ì¼í† í°ê²€ì¦_FAIL_EMAIL_VERIFICATION_CODE_EXPIRED:
                value: "{\"token\":null}"
              ì´ë©”ì¼í† í°ê²€ì¦_FAIL_EMAIL_VERIFICATION_CODE_NOT_MATCHED:
                value: "{\"token\":\"testToken\"}"
              ì´ë©”ì¼í† í°ê²€ì¦_SUCCESS:
                value: "{\"token\":\"testToken\"}"
      responses:
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-2094128924"
              examples:
                ì´ë©”ì¼í† í°ê²€ì¦_FAIL_EMAIL_VERIFICATION_CODE_EXPIRED:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C021\",\"data\":null}"
                ì´ë©”ì¼í† í°ê²€ì¦_FAIL_EMAIL_VERIFICATION_CODE_NOT_MATCHED:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C022\",\"data\":null}"
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-login-2094128924"
              examples:
                ì´ë©”ì¼í† í°ê²€ì¦_SUCCESS:
                  value: "{\"status\":\"OK\",\"code\":\"A001\",\"data\":null}"
components:
  schemas:
    api-auth-login-2094128924:
      type: object
      properties:
        code:
          type: string
          description: ìƒíƒœ ì½”ë“œ
        status:
          type: string
          description: ì‘ë‹µ ìƒíƒœ
    api-auth-login-997914088:
      type: object
      properties:
        code:
          type: string
          description: ìƒíƒœ ì½”ë“œ
        data:
          type: object
          properties:
            accessToken:
              type: string
              description: access token
            email:
              type: string
              description: email
            refreshToken:
              type: string
              description: refresh token
          description: data
        status:
          type: string
          description: ì‘ë‹µ ìƒíƒœ
    api-auth-login486549215:
      type: object
