openapi: 3.0.1
info:
  title: ê·¸ë¦°ë£¸ API DOCUMENT
  description: ê·¸ë¦°ë£¸ api ëª…ì„¸ì„œì…ë‹ˆë‹¤.
  version: 0.1.0
servers:
- url: http://localhost:8080
- url: https://greenroom-server:8080
- url: http://greenroom-server:8080
tags: []
paths:
  /api/auth/login:
    post:
      tags:
      - ğŸ˜ AUTH-ì¸ì¦/ì¸ê°€
      summary: ë¡œê·¸ì¸ ìš”ì²­ api
      description: email&password ê¸°ë°˜ ì¼ë°˜ ë¡œê·¸ì¸ api
      operationId: ë¡œê·¸ì¸
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/api-auth-tokens486549215"
            examples:
              ë¡œê·¸ì¸-ì„±ê³µ:
                value: "{\"email\":\"testEmail@gmail.com\",\"password\":\"!123456\"\
                  }"
              ë¡œê·¸ì¸_FAIL_PASSWORD_NOT_MATCHED:
                value: "{\"email\":\"testEmail@gmail.com\",\"password\":\"!1234567890\"\
                  }"
              ë¡œê·¸ì¸_FAIL_USER_NOT_FOUND:
                value: "{\"email\":\"testEmail@gmail.com\",\"password\":\"!123456\"\
                  }"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-997914088"
              examples:
                ë¡œê·¸ì¸-ì„±ê³µ:
                  value: "{\"status\":\"OK\",\"code\":\"A001\",\"data\":{\"email\"\
                    :\"testEmail@gmail.com\",\"accessToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6IkdVRVNULEdFTkVSQUwiLCJleHAiOjE3MzYxNDU4Mzh9.iYYf8TMg8c9MtxdQFC9k16TUu_sc4dJRBaRpw27SiZvW9ckG_dBWb89OEg_dpp7htVNdzBhFbJn144bOBhN_gQ\"\
                    ,\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiZXhwIjoxNzM3MzUxODM4fQ.54_vaYgzRRAi5niRY3doyFRsuh-2g2Rxy8QcF6EA1NTrjik4NW2WSj0cHzFe2BAkhp08lddiUllGN86XESUPzQ\"\
                    }}"
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-2094128924"
              examples:
                ë¡œê·¸ì¸_FAIL_PASSWORD_NOT_MATCHED:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C017\",\"data\":null}"
        "404":
          description: "404"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-2094128924"
              examples:
                ë¡œê·¸ì¸_FAIL_USER_NOT_FOUND:
                  value: "{\"status\":\"NOT_FOUND\",\"code\":\"C001\",\"data\":null}"
  /api/auth/signup:
    post:
      tags:
      - ğŸ˜ AUTH-ì¸ì¦/ì¸ê°€
      summary: íšŒì›ê°€ì… ìš”ì²­ api
      description: emailê³¼ passwordë¡œ íšŒì›ê°€ì…ì„ ìš”ì²­í•©ë‹ˆë‹¤. ì¸ì¦ëœ emailë§Œ íšŒì›ê°€ì…ì´ ê°€ëŠ¥í•©ë‹ˆë‹¤.
      operationId: íšŒì›ê°€ì…
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/api-auth-tokens486549215"
            examples:
              íšŒì›ê°€ì…-ì„±ê³µ:
                value: "{\"email\":\"testEmail@gmail.com\",\"password\":\"!123456\"\
                  }"
              íšŒì›ê°€ì…_FAIL_EMAIL_NOT_VERIFIED:
                value: "{\"email\":\"emailnotvierified@gmail.com\",\"password\":\"\
                  !123456\"}"
              íšŒì›ê°€ì…_FAIL_USER_ALREAD_EXISTS:
                value: "{\"email\":\"testEmail@gmail.com\",\"password\":\"!123456\"\
                  }"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-2094128924"
              examples:
                íšŒì›ê°€ì…-ì„±ê³µ:
                  value: "{\"status\":\"CREATED\",\"code\":\"A001\",\"data\":null}"
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-2094128924"
              examples:
                íšŒì›ê°€ì…_FAIL_EMAIL_NOT_VERIFIED:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C023\",\"data\":null}"
                íšŒì›ê°€ì…_FAIL_USER_ALREAD_EXISTS:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C002\",\"data\":null}"
  /api/auth/tokens:
    put:
      tags:
      - ğŸ˜ AUTH-ì¸ì¦/ì¸ê°€
      summary: jwt í† í° ê°±ì‹  ìš”ì²­ api
      description: refresh tokenì„ í†µí•´ access token & refresh token ëª¨ë‘ ê°±ì‹ 
      operationId: jwtToken_ì¬ë°œê¸‰_
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/api-auth-tokens486549215"
            examples:
              jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_EXPIRED:
                value: "{\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6W3siYXV0aG9yaXR5IjoiZ3Vlc3QifSx7ImF1dGhvcml0eSI6ImdlbmVyYWwifV0sImV4cCI6MTczNjE0MjIzN30.MIOdP18AkkSM9vitjVMI2YttrQzYZNgBKptYBJVEaFlY5yQa6JcyUP6ff5mEaYCOkiD7jfOWLINLOjiEI9uVIA\"\
                  }"
              jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_INVALID:
                value: "{\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6W3siYXV0aG9yaXR5IjoiZ3Vlc3QifSx7ImF1dGhvcml0eSI6ImdlbmVyYWwifV0sImV4cCI6MTczNjE0MjIzN30.amQMQmS16BR5l7EahIucIsLDCpP2J6r671dCbv47CAVa4hRwqyD3HqlzEVW804I2cnI7RS2Du8vlI6-2D_kIPw\"\
                  }"
              jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_NOT_EXISTS:
                value: "{\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6W3siYXV0aG9yaXR5IjoiZ3Vlc3QifSx7ImF1dGhvcml0eSI6ImdlbmVyYWwifV0sImV4cCI6MTczNjE0MjIzOH0.Uef7VFjbNXJzXTmrRl8YW7qFx0EhDjND1eNJY293EggCBUw15StTq37eNc18ChAeYSNAf2eXrR0axSAd-qEkZw\"\
                  }"
              jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_NOT_MATCHED:
                value: "{\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6W3siYXV0aG9yaXR5IjoiZ3Vlc3QifSx7ImF1dGhvcml0eSI6ImdlbmVyYWwifV0sImV4cCI6MTczNjE0MjIzOH0.Uef7VFjbNXJzXTmrRl8YW7qFx0EhDjND1eNJY293EggCBUw15StTq37eNc18ChAeYSNAf2eXrR0axSAd-qEkZw\"\
                  }"
              jwtToken_ì¬ë°œê¸‰_FAIL_USER_NOT_FOUND:
                value: "{\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6W3siYXV0aG9yaXR5IjoiZ3Vlc3QifSx7ImF1dGhvcml0eSI6ImdlbmVyYWwifV0sImV4cCI6MTczNjE0MjIzOH0.Uef7VFjbNXJzXTmrRl8YW7qFx0EhDjND1eNJY293EggCBUw15StTq37eNc18ChAeYSNAf2eXrR0axSAd-qEkZw\"\
                  }"
              jwtToken_ì¬ë°œê¸‰_SUCCESS:
                value: "{\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiZXhwIjoxNzM3MzUxODMyfQ.0_3GpCK2w_cF1zbS7bKJeDhO9YM6594iyXmibDkyqMj9GYqL4gU6P5KeeNONGOghpb9E-2tXzbuH7wc5SfJxrQ\"\
                  }"
      responses:
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-2094128924"
              examples:
                jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_EXPIRED:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C005\",\"data\":null}"
                jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_INVALID:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C009\",\"data\":null}"
                jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_NOT_MATCHED:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C007\",\"data\":null}"
        "404":
          description: "404"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-2094128924"
              examples:
                jwtToken_ì¬ë°œê¸‰_FAIL_REFRESH_TOKEN_NOT_EXISTS:
                  value: "{\"status\":\"NOT_FOUND\",\"code\":\"C026\",\"data\":null}"
                jwtToken_ì¬ë°œê¸‰_FAIL_USER_NOT_FOUND:
                  value: "{\"status\":\"NOT_FOUND\",\"code\":\"C001\",\"data\":null}"
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-997914088"
              examples:
                jwtToken_ì¬ë°œê¸‰_SUCCESS:
                  value: "{\"status\":\"OK\",\"code\":\"A001\",\"data\":{\"email\"\
                    :\"testEmail@gmail.com\",\"accessToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiYXV0aCI6IkdVRVNULEdFTkVSQUwiLCJleHAiOjE3MzYxNDU4MzJ9.r4I38fdXEPygrJhiVmRFbM9_zcEjaQwGpxochsJFgVVYQPpaVMeD-beTaktlT0aqVvW6RW0TtmbFTmm8JD4s3w\"\
                    ,\"refreshToken\":\"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0RW1haWxAZ21haWwuY29tIiwiZXhwIjoxNzM3MzUxODMyfQ.0_3GpCK2w_cF1zbS7bKJeDhO9YM6594iyXmibDkyqMj9GYqL4gU6P5KeeNONGOghpb9E-2tXzbuH7wc5SfJxrQ\"\
                    }}"
  /api/auth/email/authentication:
    put:
      tags:
      - ğŸ˜ AUTH-ì¸ì¦/ì¸ê°€
      summary: ì´ë©”ì¼ ì¸ì¦ ìš”ì²­ api
      description: ì´ë©”ì¼ ì¸ì¦ìš© ë”¥ë§í¬ ë©”ì¼ ì „ì†¡ & ì¸ì¦ ì½”ë“œ ìƒì„± api
      operationId: ì´ë©”ì¼ì¸ì¦_
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/api-auth-tokens486549215"
            examples:
              ì´ë©”ì¼ì¸ì¦_FAIL_ALREADY_VERIFIED_EMAIL:
                value: "{\"redirectUrl\":\"http://localhost:8080\",\"email\":\"emailTest@gmail.com\"\
                  }"
              ì´ë©”ì¼ì¸ì¦_FAIL_EXCEED_NUMBER_OF_TRIAL_VERIFICATION:
                value: "{\"redirectUrl\":\"http://localhost:8080\",\"email\":\"emailTest@gmail.com\"\
                  }"
              ì´ë©”ì¼ì¸ì¦_FAIL_FAIL_TO_SEND_EMAIL:
                value: "{\"redirectUrl\":\"http://localhost:8080\",\"email\":\"mygongjoo@naver.com\"\
                  }"
              ì´ë©”ì¼ì¸ì¦_FAIL_INVALID_EMAIL_CONTENT:
                value: "{\"redirectUrl\":\"http://localhost:8080\",\"email\":\"myr@@@@naver.com\"\
                  }"
              ì´ë©”ì¼ì¸ì¦_FAIL_VERIFIED_USER_ALREADY_EXISTS:
                value: "{\"redirectUrl\":\"http://localhost:8080\",\"email\":\"emailTest@gmail.com\"\
                  }"
              ì´ë©”ì¼ì¸ì¦_SUCCESS:
                value: "{\"redirectUrl\":\"http://localhost:8080\",\"email\":\"emailTest@gmail.com\"\
                  }"
      responses:
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-2094128924"
              examples:
                ì´ë©”ì¼ì¸ì¦_FAIL_ALREADY_VERIFIED_EMAIL:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C025\",\"data\":null}"
                ì´ë©”ì¼ì¸ì¦_FAIL_EXCEED_NUMBER_OF_TRIAL_VERIFICATION:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C019\",\"data\":null}"
                ì´ë©”ì¼ì¸ì¦_FAIL_INVALID_EMAIL_CONTENT:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C024\",\"data\":null}"
                ì´ë©”ì¼ì¸ì¦_FAIL_VERIFIED_USER_ALREADY_EXISTS:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C018\",\"data\":null}"
        "500":
          description: "500"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-2094128924"
              examples:
                ì´ë©”ì¼ì¸ì¦_FAIL_FAIL_TO_SEND_EMAIL:
                  value: "{\"status\":\"INTERNAL_SERVER_ERROR\",\"code\":\"D002\"\
                    ,\"data\":null}"
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-2094128924"
              examples:
                ì´ë©”ì¼ì¸ì¦_SUCCESS:
                  value: "{\"status\":\"OK\",\"code\":\"A001\",\"data\":null}"
  /api/auth/email/token/authentication:
    put:
      tags:
      - ğŸ˜ AUTH-ì¸ì¦/ì¸ê°€
      summary: ì´ë©”ì¼ í† í° ê²€ì¦ ìš”ì²­ api
      description: ì´ë©”ì¼ ë§í¬ë¥¼ í†µí•´ ì œê³µë°›ì€ í† í°ì„ ê²€ì¦í•˜ëŠ” api
      operationId: ì´ë©”ì¼í† í°ê²€ì¦_
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/api-auth-tokens486549215"
            examples:
              ì´ë©”ì¼í† í°ê²€ì¦_FAIL_EMAIL_VERIFICATION_CODE_EXPIRED:
                value: "{\"token\":null}"
              ì´ë©”ì¼í† í°ê²€ì¦_FAIL_EMAIL_VERIFICATION_CODE_NOT_MATCHED:
                value: "{\"token\":\"testToken\"}"
              ì´ë©”ì¼í† í°ê²€ì¦_SUCCESS:
                value: "{\"token\":\"testToken\"}"
      responses:
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-2094128924"
              examples:
                ì´ë©”ì¼í† í°ê²€ì¦_FAIL_EMAIL_VERIFICATION_CODE_EXPIRED:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C021\",\"data\":null}"
                ì´ë©”ì¼í† í°ê²€ì¦_FAIL_EMAIL_VERIFICATION_CODE_NOT_MATCHED:
                  value: "{\"status\":\"CONFLICT\",\"code\":\"C022\",\"data\":null}"
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-auth-tokens-2094128924"
              examples:
                ì´ë©”ì¼í† í°ê²€ì¦_SUCCESS:
                  value: "{\"status\":\"OK\",\"code\":\"A001\",\"data\":null}"
components:
  schemas:
    api-auth-tokens-2094128924:
      type: object
      properties:
        code:
          type: string
          description: ìƒíƒœ ì½”ë“œ
        status:
          type: string
          description: ì‘ë‹µ ìƒíƒœ
    api-auth-tokens-997914088:
      type: object
      properties:
        code:
          type: string
          description: ìƒíƒœ ì½”ë“œ
        data:
          type: object
          properties:
            accessToken:
              type: string
              description: access token
            email:
              type: string
              description: email
            refreshToken:
              type: string
              description: refresh token
          description: data
        status:
          type: string
          description: ì‘ë‹µ ìƒíƒœ
    api-auth-tokens486549215:
      type: object
